#ifndef LOTTIE_QUICK_GLOBAL_H
#define LOTTIE_QUICK_GLOBAL_H

#include <QtGlobal>

#ifdef LOTTIE_QUICK_BUILD_LIBRARY
#define LOTTIE_QUICK_EXPORT Q_DECL_EXPORT
#else
#define LOTTIE_QUICK_EXPORT Q_DECL_IMPORT
#endif

#endif // LOTTIE_QUICK_GLOBAL_H
