name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:

  sailfishos:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Build
        uses: dseight/sailfishos-build-action@master
        with:
          version: 4.1.0.24
          arch: armv7hl

  ubuntu:
    runs-on: ubuntu-latest
    env:
      OPTFLAGS: -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Install dependencies
        run: >
          sudo apt-get update
          && sudo apt-get install -yq qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev
      -
        name: Configure
        env:
          CFLAGS: ${{ env.OPTFLAGS }}
          CXXFLAGS: ${{ env.OPTFLAGS }}
        run: >
          cmake
          -DCMAKE_VERBOSE_MAKEFILE=ON
          -DCMAKE_BUILD_TYPE=Release
          -DLOTTIE_QUICK_BUILD_EXAMPLE=ON
          .
      -
        name: Build
        run: make -j$(getconf _NPROCESSORS_ONLN)
